project:
  type: website

website:
  title: "Biomedical Data Science"

  navbar:
    background: transparent
    search: true
    right:
      - text: About
        file: index.qmd

      - text: Contact
        file: contact.qmd

      - icon: github
        href: https://github.com/imkhoibui

  sidebar:
    style: "floating"
    
    contents:
      - section: "Inference"
        contents:
          - inference/introduction.qmd
          - inference/clt.qmd
          - inference/power-cal.qmd
          - inference/monte-carlo.qmd
      - section: "EDA"
        contents:

      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



